name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
#  call-update_readme:
#    uses: costateixeira/ig-badges/.github/workflows/update_readme.yaml@main    
#    with:
#      token: costateixeira
#      repo: mynewig
#      branch: main
 

  web-deploy:
    name: Ubuntu VM
    runs-on: ubuntu-latest
    steps:
    
    - name: Getting latest Code
      uses: actions/checkout@v2.3.2    
    
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O README_SRC.md https://raw.githubusercontent.com/costateixeira/ig-badges/main/README_SRC.md    
      
    - name: Create readme
      run: cp README_SRC.md README3.md

    - name: Replace text
      run: |
        sed -i -e "s|__GH_OWNER__|${GITHUB_REPOSITORY_OWNER}|g" README3.md
        sed -i -e "s|__GH_BRANCH__|${GITHUB_REF##*/}|g"         README3.md
        sed -i -e "s|__GH_REPO__|${GITHUB_REPOSITORY##*/}|g"    README3.md
    - run: ls
    - name: stage changed files
      run: git add .


    - name: Deploy candidate
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
#        branch: ${GITHUB_REF##*/} # The branch the action should deploy to.
        branch: main # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
        commit-message: Deploy branch
        target-folder: .
        clean: false 

      
#  call_build: 
#    uses: openhie/empty-fhir-ig/.github/workflows/main.yml@master

 
    

 
